# Generated by Django 4.1.3 on 2022-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_issue',
            name='book_instance',
        ),
        migrations.RemoveField(
            model_name='book_issue',
            name='student',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Book_Issue',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
