# Generated by Django 4.1.3 on 2022-11-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_book_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_book',
            new_name='issue_book',
        ),
    ]
