# Generated by Django 4.1.3 on 2022-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_add_book_issue_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_book',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
